import {
  Home,
  Users,
  Gauge,
  MapPin,
  Route,
  ClipboardList,
  ScanLine,
  BarChart3,
  Download,
  FileText,
  Settings,
  Shield,
  AlertTriangle,
  Building2,
  Brain,
  TrendingUp,
  ShieldAlert,
  Droplets,
  Activity,
  Crown,
} from 'lucide-react';

export const APP_NAME = 'Vertiente Reader';
export const APP_DESCRIPTION = 'Sistema de Gestión de Lectura de Medidores de Agua';

export const NAVIGATION_ITEMS = [
  {
    label: 'Home',
    href: '/',
    icon: Home,
    color: '#0A84FF',
    roles: ['root', 'administrador', 'supervisor', 'operario', 'lector'],
  },
  {
    label: 'Clientes',
    href: '/clientes',
    icon: Users,
    color: '#34C759',
    roles: ['root', 'administrador', 'supervisor', 'lector'],
  },
  {
    label: 'Medidores',
    href: '/medidores',
    icon: Gauge,
    color: '#FF9F0A',
    roles: ['root', 'administrador', 'supervisor', 'lector'],
  },
  {
    label: 'Zonas',
    href: '/zonas',
    icon: MapPin,
    color: '#30D158',
    roles: ['root', 'administrador', 'supervisor', 'lector'],
  },
  {
    label: 'Rutas',
    href: '/rutas',
    icon: Route,
    color: '#BF5AF2',
    roles: ['root', 'administrador', 'supervisor', 'lector'],
  },
  {
    label: 'Asignaciones',
    href: '/asignaciones',
    icon: ClipboardList,
    color: '#5E5CE6',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Lecturas',
    href: '/lecturas',
    icon: ScanLine,
    color: '#32ADE6',
    roles: ['root', 'administrador', 'supervisor', 'operario', 'lector'],
  },
  {
    label: 'Dashboards',
    href: '/lecturas/dashboard',
    icon: BarChart3,
    color: '#0A84FF',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Exportar',
    href: '/integracion/exportar',
    icon: Download,
    color: '#8E8E93',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Reportes',
    href: '/reportes',
    icon: FileText,
    color: '#30B0C7',
    roles: ['root', 'administrador', 'supervisor', 'operario', 'lector'],
  },
  {
    label: 'Usuarios',
    href: '/usuarios',
    icon: Users,
    color: '#AF52DE',
    roles: ['root', 'administrador'],
  },
  {
    label: 'Empresas',
    href: '/empresas',
    icon: Building2,
    color: '#FF6B35',
    roles: ['root', 'administrador'],
  },
  {
    label: 'Configuracion',
    href: '/configuracion',
    icon: Settings,
    color: '#636366',
    roles: ['root', 'administrador'],
  },
  {
    label: 'Auditoria',
    href: '/auditoria',
    icon: Shield,
    color: '#FF453A',
    roles: ['root', 'administrador'],
  },
  {
    label: 'Incidencias',
    href: '/incidencias',
    icon: AlertTriangle,
    color: '#FF9F0A',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Anomalias IA',
    href: '/anomalias',
    icon: Brain,
    color: '#FF453A',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Predicciones',
    href: '/predicciones',
    icon: TrendingUp,
    color: '#30D158',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Riesgos',
    href: '/riesgos',
    icon: ShieldAlert,
    color: '#FF6B3D',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Panel ANF',
    href: '/dashboard-anf',
    icon: Droplets,
    color: '#64D2FF',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Panel Operativo',
    href: '/dashboard-operativo',
    icon: Activity,
    color: '#30D158',
    roles: ['root', 'administrador', 'supervisor'],
  },
  {
    label: 'Panel Ejecutivo',
    href: '/dashboard-ejecutivo',
    icon: Crown,
    color: '#FFD60A',
    roles: ['root', 'administrador'],
  },
] as const;

export const ITEMS_PER_PAGE = 20;

export const ANOMALY_THRESHOLDS = {
  CONSUMO_ALTO_PORCENTAJE: 200,
  CONSUMO_BAJO_PORCENTAJE: 20,
  PERIODOS_MEDIDOR_PARADO: 2,
};
